#ifndef MODULE4G_TASK_FHQ_20190722_H
#define MODULE4G_TASK_FHQ_20190722_H


#if defined(__cplusplus)
extern "C" {     /* Make sure we have C-declarations in C++ programs */
#endif

typedef enum{
MODULE4G_MSG_SEND_DATA,
MODULE4G_MSG_PARSE_DATA,
MODULE4G_MSG_STARTUP,
MODULE4G_MSG_DOWNLOAD_FINISH,
MODULE4G_MSG_MAX	
}enumModule4GMsg;

typedef enum{
AT_4G_CMD_CMEE,
AT_4G_CMD_GET_PBREADY,
AT_4G_CMD_GET_SIM,
AT_4G_CMD_GET_KSUP,
AT_4G_CMD_SET_CPIN,
AT_4G_CMD_SET_COPS, //5
AT_4G_CMD_SET_CSQ,  
AT_4G_CMD_SET_CGCAT,
AT_4G_CMD_CGDCONT, 
AT_4G_CMD_KCNXCFG,
AT_4G_CMD_KCNXUP,   //10
AT_4G_CMD_KCGPADDR,
AT_4G_CMD_KUDPCFG, 
//AT_4G_CMD_KTCPCNX, 
AT_4G_CMD_KCNXIND,
AT_4G_CMD_KUDPIND, 
AT_4G_CMD_KUDPSEND,//15
AT_4G_CMD_KCNXTIMER, 
AT_4G_CMD_SET_CGREG, 
AT_4G_CMD_SET_CIMI,
AT_4G_CMD_CGSN,	
AT_4G_CMD_UDP_NOTIF,   //20
AT_4G_CMD_READY_TO_SEND,
//AT_4G_CMD_CFUN,  
//AT_4G_CMD_CIMI, //10
//AT_4G_CMD_CMGF,
//AT_4G_CMD_CNMI,		
//AT_4G_CMD_CEDRXS,	
//AT_4G_CMD_SQNSCFG,   
//AT_4G_CMD_SQNSCFGEXT, //15
//AT_4G_CMD_SQNSD,
//AT_4G_CMD_SQNSSENDEXT,	
//AT_4G_CMD_SQNDRDY,
//AT_4G_CMD_NEW_SMS,  
//AT_4G_CMD_CMGR, //20
//AT_4G_CMD_CMGD,	
//AT_4G_CMD_READY_TO_SEND,
//AT_4G_CMD_WS46,

AT_4G_CMD_KHTTPCFG,
AT_4G_CMD_KHTTPCNX,
AT_4G_CMD_KHTTPHEADER,
AT_4G_CMD_KHTTPGET,
AT_4G_CMD_KHTTPHEAD,
AT_4G_CMD_KHTTPPOST,
AT_4G_CMD_KHTTPCLOSE,
AT_4G_CMD_KHTTPDEL,
AT_4G_CMD_KHTTP_IND,

AT_4G_CMD_KHTTPSCFG,
AT_4G_CMD_KHTTPSCNX,
AT_4G_CMD_KHTTPSHEADER,
AT_4G_CMD_KHTTPSGET,
AT_4G_CMD_KHTTPSHEAD,
AT_4G_CMD_KHTTPSPOST,
AT_4G_CMD_KHTTPSCLOSE,
AT_4G_CMD_KHTTPSDEL,
AT_4G_CMD_KHTTPS_IND,
AT_4G_CMD_MAX		
}enumATCmd;

typedef enum{
MODULE4G_REG_DISABLE,
MODULE4G_REG_ENABLE,
MODULE4G_REG_WITH_LOCATION,
MODULE4G_REG_WITH_MORE,
MODULE4G_REG_MAX
}enumModule4GReg;

typedef enum{
MODULE4G_FUN_MIN,
MODULE4G_FUN_FULL,
MODULE4G_FUN_DISABLE_TX,
MODULE4G_FUN_DISABLE_RX,
MODULE4G_FUN_DISABLE_TX_AND_RX,
MODULE4G_FUN_MAX
}enumModule4GFun;

typedef enum{
MODULE4G_CMGF_PDF,
MODULE4G_CMGF_TEXT,

MODULE4G_CMGF_MAX
}enumModule4GCMGF;

typedef enum{
MODULE4G_CGSN_SN,
MODULE4G_CGSN_IMEI,
MODULE4G_CGSN_IMEISV,
MODULE4G_CGSN_SVN,
MODULE4G_CGSN_MAX
}enumModuleCGSN;

typedef enum{
MODULE4G_POWER_STEP_BAND,
MODULE4G_POWER_STEP_CEDRXS,
MODULE4G_POWER_STEP_CFUN,
MODULE4G_POWER_STEP_CIMI,
MODULE4G_POWER_STEP_CGSN,
MODULE4G_POWER_STEP_WS46,
MODULE4G_POWER_STEP_CMGF,
MODULE4G_POWER_STEP_CNMI,
MODULE4G_POWER_STEP_SQNSCFG,
MODULE4G_POWER_STEP_SQNSCFG_EXT,
MODULE4G_POWER_STEP_SQNSD,
MODULE4G_POWER_STEP_SQNSD_EXT,
MODULE4G_POWER_STEP_START_COMPLETE,
MODULE4G_POWER_STEP_MAX	
}enumModule4GPowerStep;

void module4g_task_post_message(int msg, uint32_t wPara, int lpPara);
bool module4g_task_send_at_cmd(int cmd, char* strFormat, ...);
void module4g_task(void *pvParameters);
void module_check_enable_to_send(void);
void idle_lte_socket_set_callback_func(void);
int * getSynchronousLenPtr(void);
char * module4g_task_send_synchronous_cmd(const char * pString);
char * module4g_task_get_synchronous_result(int cmd, char* strFormat, ...);
char * getATCmdByIndex(int iIndex);
int parseRecevieCmd(char * pCmd);
#if defined(__cplusplus)
}
#endif 

#endif	//MODULE4G_TASK_FHQ_20190722_H

