/*
 * Generated by MTK Easy PinMux Tool Version 2.4.1 for 2523. Copyright MediaTek Inc. (C) 2015.
 * 2019-09-20 11:11:48:0368
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const char BSP_WIFI_RESET_PIN = 0;
const char BSP_WIFI_RESET_PIN_M_GPIO = 0;
const char BSP_WIFI_RESET_PIN_M_EINT = 1;
const char BSP_WIFI_RESET_PIN_M_AUXADCIN_0 = 2;
const char BSP_WIFI_RESET_PIN_M_U2RXD = 3;
const char BSP_WIFI_RESET_PIN_M_PWM0 = 4;
const char BSP_WIFI_RESET_PIN_M_MA_SPI1_A_CS = 5;
const char BSP_WIFI_RESET_PIN_M_MA_EDIDO = 6;
const char BSP_WIFI_RESET_PIN_M_MA_SPI0_A_CS = 7;
const char BSP_WIFI_RESET_PIN_M_DEBUGMON11 = 8;
const char BSP_WIFI_RESET_PIN_M_BTJTDO = 9;


const char BSP_GNSS_POWER_PIN = 1;
const char BSP_GNSS_POWER_PIN_M_GPIO = 0;
const char BSP_GNSS_POWER_PIN_M_EINT = 1;
const char BSP_GNSS_POWER_PIN_M_AUXADCIN_1 = 2;
const char BSP_GNSS_POWER_PIN_M_U2TXD = 3;
const char BSP_GNSS_POWER_PIN_M_PWM1 = 4;
const char BSP_GNSS_POWER_PIN_M_MA_SPI1_A_SCK = 5;
const char BSP_GNSS_POWER_PIN_M_MA_EDIDI = 6;
const char BSP_GNSS_POWER_PIN_M_MA_SPI0_A_SCK = 7;
const char BSP_GNSS_POWER_PIN_M_DEBUGMON12 = 8;
const char BSP_GNSS_POWER_PIN_M_BTDBGACKN = 9;


const char BSP_WIFI_32K_PIN = 14;
const char BSP_WIFI_32K_PIN_M_GPIO = 0;
const char BSP_WIFI_32K_PIN_M_EINT = 1;
const char BSP_WIFI_32K_PIN_M_CLKO = 2;
const char BSP_WIFI_32K_PIN_M_MA_EDICK = 3;
const char BSP_WIFI_32K_PIN_M_MA_SPI1_B_MISO = 4;
const char BSP_WIFI_32K_PIN_M_PWM3 = 5;
const char BSP_WIFI_32K_PIN_M_SLA_EDICK = 6;


const char WIFI_WAKUP_PIN = 15;
const char WIFI_WAKUP_PIN_M_GPIO = 0;
const char WIFI_WAKUP_PIN_M_EINT = 1;
const char WIFI_WAKUP_PIN_M_PWM4 = 5;

const char HAL_KEYPAD_COL2_PIN = 18;
const char HAL_KEYPAD_COL2_PIN_M_GPIO = 0;
const char HAL_KEYPAD_COL2_PIN_M_KCOL2 = 1;
const char HAL_KEYPAD_COL2_PIN_M_U1RXD = 2;
const char HAL_KEYPAD_COL2_PIN_M_U3RXD = 3;
const char HAL_KEYPAD_COL2_PIN_M_TRACEDATA0 = 5;
const char HAL_KEYPAD_COL2_PIN_M_LSCE1_B1 = 6;
const char HAL_KEYPAD_COL2_PIN_M_DEBUGMON6 = 7;
const char HAL_KEYPAD_COL2_PIN_M_JTDI = 8;
const char HAL_KEYPAD_COL2_PIN_M_BTJTDI = 9;


const char HAL_KEYPAD_COL0_PIN = 20;
const char HAL_KEYPAD_COL0_PIN_M_GPIO = 0;
const char HAL_KEYPAD_COL0_PIN_M_KCOL0 = 1;
const char HAL_KEYPAD_COL0_PIN_M_GPSFSYNC = 2;
const char HAL_KEYPAD_COL0_PIN_M_U0CTS = 3;
const char HAL_KEYPAD_COL0_PIN_M_SDA2 = 4;
const char HAL_KEYPAD_COL0_PIN_M_MA_SPI2_CS1 = 6;
const char HAL_KEYPAD_COL0_PIN_M_DEBUGMON7 = 7;


const char HAL_KEYPAD_ROW1_PIN = 22;
const char HAL_KEYPAD_ROW1_PIN_M_GPIO = 0;
const char HAL_KEYPAD_ROW1_PIN_M_KROW1 = 1;
const char HAL_KEYPAD_ROW1_PIN_M_U1TXD = 2;
const char HAL_KEYPAD_ROW1_PIN_M_U3TXD = 3;
const char HAL_KEYPAD_ROW1_PIN_M_TRACEDATA2 = 5;
const char HAL_KEYPAD_ROW1_PIN_M_TRACE_SWV = 6;
const char HAL_KEYPAD_ROW1_PIN_M_DEBUGMON5 = 7;
const char HAL_KEYPAD_ROW1_PIN_M_JTDO = 8;
const char HAL_KEYPAD_ROW1_PIN_M_BTDBGIN = 9;


const char BSP_WIFI_ENABLE_PIN = 48;
const char BSP_WIFI_ENABLE_PIN_M_GPIO = 0;
const char BSP_WIFI_ENABLE_PIN_M_MA_SPI3_CS1 = 1;
const char BSP_WIFI_ENABLE_PIN_M_DEBUGMON5 = 7;

/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char BSP_CTP_SW_I2C_SCL_PIN = 0xff;
const char BSP_CTP_SW_I2C_SDA_PIN = 0xff;
const char BSP_CTP_RST_PIN = 0xff;
const char BSP_CTP_EINT_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_BIO_SENSOR_PPG_VDRV_EN = 0xff;
const char BSP_BIO_SENSOR_32K = 0xff;
const char BSP_BIO_SENSOR_RST_PORT_PIN = 0xff;
const char BSP_BIO_SENSOR_AFE_PWD_PIN = 0xff;
const char BSP_WIFI_26M_PIN = 0xff;
const char BSP_HP_ANA_SW_PIN = 0xff;
const char UPDATE_HOST_STATUS_PIN = 0xff;
const char QUERY_MODEM_STATUS_PIN = 0xff;
const char NOTIFY_MODEM_EXCEPTION_PIN = 0xff;
const char TRIGGER_MODEM_RESET_PIN = 0xff;
const char NOTIFY_MODEM_WAKEUP_PIN = 0xff;
const char TRIGGER_MODEM_START_PIN = 0xff;
const char TRIGGER_MODEM_WAKEUP_PIN = 0xff;
const char BSP_LED0_PIN = 0xff;
const char BSP_LED1_PIN = 0xff;
const char BSP_LED2_PIN = 0xff;
const char BSP_EINTKEY0_PIN = 0xff;
const char BSP_EINTKEY1_PIN = 0xff;
const char BSP_EINTKEY2_PIN = 0xff;


const char HAL_KEYPAD_COL1_PIN = 0xff;
const char HAL_KEYPAD_ROW2_PIN = 0xff;
const char HAL_KEYPAD_ROW0_PIN = 0xff;
const char HAL_I2S_MASTER_EDIDO_PIN = 0xff;
const char HAL_I2S_MASTER_EDIDI_PIN = 0xff;
const char HAL_I2S_MASTER_EDIWS_PIN = 0xff;
const char HAL_I2S_MASTER_EDICK_PIN = 0xff;





