/*
 * Generated by MTK Easy PinMux Tool Version 2.4.1 for 2523. Copyright MediaTek Inc. (C) 2015.
 * 2019-09-20 11:11:48:0374
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const unsigned char WIFI_EINT_HOST = 5;
const unsigned char BSP_GNSS_EINT = 10;
const unsigned char BSP_CTP_EINT = 0xff;
const unsigned char HAL_ACCDET_EINT = 0xff;
const unsigned char HAL_MSDC_EINT = 0xff;
const unsigned char BSP_WIFI_EINT = 0xff;
const unsigned char MODEM_EXCEPTION_EINT = 0xff;
const unsigned char MODEM_WAKEUP_EINT = 0xff;
const unsigned char BSP_EINTKEY0_EINT = 0xff;
const unsigned char BSP_EINTKEY1_EINT = 0xff;
const unsigned char BSP_EINTKEY2_EINT = 0xff;



